### ISSUE TITLE
Multiple async call depending on previous one

### ISSUE THREAD

**Issue by jc-paris** [Thomvis/BrightFutures#127]
Hi,

I love BrighFutures, but I ran in an issue... I've got that piece of code :
```swift 
class func signIn(email: String, password: String) -> Future<User, Error>
    {
        let promise = Promise<User, Error>()
        UserService.signIn(email, password: password)
            .onSuccess { user in
                
                UserLocalDataStore.saveUser(user)
                    .onSuccess {
                        promise.success(user)
                    }
                    .onFailure { error in promise.failure(error) }
            }
            .onFailure { error in promise.failure(error) }

        return promise.future
    }
```

It's very annoying to have embedded success/failure call inside `.onSuccess`. Therefore, sometime I have 3, 4 or 5 call that depends on previous result.

Is there something in BrightFutures that I missed that could do what I'm doing right now in a prettier way ?

Thanks !

**Comment by Thomvis** [comment]
I think what you're looking for is `fatMap`. There's an [example in the README](https://github.com/Thomvis/BrightFutures#examples) and you could also browse through the tests for samples.

If you're confused about what `flatMap` does, try to use `map` first and notice how you'll end up with futures in futures (`Future<Future<Future<User, Error>, Error>, Error>`). The solution to that is `flatMap`, because it performs a `map` and then _flattens_ the nested futures.

**Comment by jc-paris** [comment]
It looks like what I might need. Thanks for the quick reply ! 
Oh and, nice talk at DotSwift'16 ;) It was from far my favorite.
