### ISSUE TITLE
Add Promises to the documentation 

### ISSUE THREAD

**Issue by hfehrmann** [Thomvis/BrightFutures#166]
There is no mention of Promises in the README. It is an important way of creating futures, so it should, at least, be mentioned in the documentation for the beginner who doesn't know about their existence.

**Comment by Thomvis** [comment]
I've seen many suboptimal usages of Promises in cases where composition would be a better option. That's why Promises have no prominent spot in the README. Instead, I push Future's `init` method that takes the resolver.

I do agree that Promises have their use and that they could be featured better in the readme. If you want to do that in a PR, that would be very welcome.
