### ISSUE TITLE
How to cancel future?

### ISSUE THREAD

**Issue by Bouke** [Thomvis/BrightFutures#17]
Say I have a long-running background calculation, that the user should be able to cancel. The current implementation does not include some communication mechanism for signalling this event. How could such a feature be implemented? I think the following concerns should be addressed:

* Signal the background calculation of the cancellation; it would be up to the future to check for this flag and stop further processing.
* Signal the promise of some "cancel" or "failure" state; so that any subsequent callbacks also recognize the cancellation of the promise/future.

**Comment by Thomvis** [comment]
Since our Future is primarily modeled after Scala's future, my initial reaction is: "What would Scala do?" I don't know, but a quick internet search revealed that Scala's futures are not cancellable (yet) and people miss it ([here](http://stackoverflow.com/questions/16020964/cancellation-with-future-and-promise-in-scala) and [here](http://stackoverflow.com/questions/16009837/how-to-cancel-future-in-scala)).

I agree that it is practical to be able to cancel a background calculation / future / 'task', I use this with [BFTasks](https://github.com/BoltsFramework/Bolts-iOS). I'll have to think about whether it should be part of `Future` or if it should be part of a subtype that is more like a 'task', e.g. see [ReactKit/SwiftTask](https://github.com/ReactKit/SwiftTask).

One related question: what if you cancel a future that is created from an `andThen`, `map` and the like. Would it also cancel the original future that it originates from?

I will create an issue here soon that deals with the pure vs practical future (internal) debate that I alluded to in the second paragraph and will certainly consider adding a way to cancel a future.

**Comment by Thomvis** [comment]
To answer my own question related to te propagation of cancel: probably not a good idea, see https://github.com/ReactKit/SwiftTask/pull/18.

**Comment by Bouke** [comment]
Having the cancel event propagating up the chain might not be expected indeed. However the cancel event should propagate down the chain; maybe cancelling them as well or put them in the error state.

For example:

    A -> B -> C

So when cancelling B; C should be cancelled as well, A remains untouched.

**Comment by Thomvis** [comment]
I've had the time to think about this for a while now and I feel like cancelling (and pausing) a task should not be part of a `Future`. I've started working on a wrapper around `NSProgress` that provides a way to cancel and pause a task: https://github.com/Thomvis/GoodProgress. There could eventually very well be a third library that combines BrightFutures and GoodProgress and thereby achieve the functionality that you are looking for.
