### ISSUE TITLE
Map function does not work on Futures

### ISSUE THREAD

**Issue by firemuzzy** [Thomvis/BrightFutures#19]
Applying the map function on a future seems to never finish. The map block never gets executed.  I tried debugging the map myself, even looking at the BrightFutures code by setting breakpoints there, but that has only caused xcode to seg fault (a lovely feature I keep seeing with swift). So I am stuck.

Here is the source of me using the map, the 'dummyAbbrDictF' function is the culprit.

```
func dummyStationsF() -> Future<[Station]> {
    return future {
      let expected12StSt = Station(name: "12th St. Oakland City Center", abbreviation: "12th", city: "Oakland", latitude: 37.803664, longitude: -122.271604)
      let expected16StSt = Station(name: "16th St. Mission", abbreviation: "16th", city: "San Francisco", latitude: 37.765062, longitude: -122.419694)
      let expectedMontSt = Station(name: "Montgomery St.", abbreviation: "mont", city: "San Francisco", latitude: 37.789256, longitude: -122.401407)
      let expectedRockSt = Station(name: "Rockridge", abbreviation: "rock", city: "Oakland", latitude: 37.844601, longitude: -122.251793)
      let expectedSFOSt = Station(name: "San Francisco Int'l Airport", abbreviation: "sfia", city: "San Francisco Int'l Airport", latitude: 37.616035, longitude: -122.392612)
      let expectedSSFSt = Station(name: "South San Francisco", abbreviation: "ssan", city: "South San Francisco", latitude: 37.664174, longitude: -122.444116)
      
      let stns = [expected12StSt,expected16StSt,expectedMontSt,expectedRockSt,expectedSFOSt,expectedSSFSt]
      return Result.Success(Box(stns))
    }
  }
  
  func dummyAbbrDictF() -> Future<Dictionary<String, Station>> {
    return self.dummyStationsF().map { stations -> Dictionary<String, Station> in
      var dict: Dictionary<String, Station> = [:]
      for station in stations {
        dict[station.abbreviation] = station
      }
      return dict
    }
  }
```

I also put all the code into a branch https://github.com/firemuzzy/BartApp, the 'testAbbrs' test in StationStoreTests is failing due the issue of the map function getting stuck.

**Comment by Thomvis** [comment]
Thanks for providing detailed information! It seems like your tests are causing a deadlock and that's why the map is not executed. 

In your test, you do a `forced` on the result of the map:
`store.dummyAbbrDictF().forced(1)`. This blocks the main thread for up to 1 second, expecting the map to be done by then. The map operation itself will also be executed on the main thread (the default context for a callback that is added from the main thread), but cannot execute because the main thread is already blocked by `forced()`.

To avoid this situation, I would advise against using `forced` (especially on the main thread) unless you _really_ need it, which is almost never. Instead, I'd write asynchronous tests of which you can find plenty examples in the BrightFutures tests, e.g: https://github.com/Thomvis/BrightFutures/blob/master/BrightFuturesTests/BrightFuturesTests.swift#L312.

PS: the breakpoints indeed didn't work, very annoying. I was able to get them to work however after I replaced `Station` by bool in all related calls. In my experience, most crashes have to do with formatting/displaying custom types in the debugger so then I try to get rid of them.

**Comment by firemuzzy** [comment]
Thanks for finding the issue. I used the async tests in my other stuff, but was sloppy and lazy so used forced as it was convenient. I guess that bit me back heavily.
