### ISSUE TITLE
Possible to send multiple values over time to a Future?

### ISSUE THREAD

**Issue by tonyarnold** [Thomvis/BrightFutures#34]
This is probably straying a bit into RAC's territory, but is there a way to send multiple values over time to a Future? My use case is the CLLocationManager's delegate API, where things like authorisation can return indeterminate states before returning a proper value. 

I'd prefer not to have to use some kind of "retry" mechanism, but I get this might not be the point of BF.

**Comment by Thomvis** [comment]
On numerous occasions I found myself wanting the thing you are describing. However, like you already suggest, I don't think it is something a 'future' should support. ReactiveCocoa or https://github.com/SwiftBond/Bond might be a better fit. I do imagine a library* on top of BrightFutures that uses a sequence of futures to provide the more persistent/open link you are looking for.

Let me know if you want to discuss this furtur or feel free to close this issue otherwise.


\* Possible names: SwiftySignal, CloseChannels, SuperStream, etc. :wink:

**Comment by tonyarnold** [comment]
No, I completely agree. What I like about your library is the focus — adding Signals to it would take away from that. I'll use ReactiveCocoa for that :smile:
