### ISSUE TITLE
Question about InvalidationToken()

### ISSUE THREAD

**Issue by aputinski** [Thomvis/BrightFutures#72]
Is it possible to use InvalidationTokens with `.flatMap()`?

**Comment by Thomvis** [comment]
At the moment not, no. It could be added easily, so feel free to create a PR. We could also leave this issue open until I have time to add it.

**Comment by aputinski** [comment]
I took a stab at it, but I'm afraid I'm still grappling with Swift generics :/

**Comment by Thomvis** [comment]
In a recent commit (https://github.com/Thomvis/BrightFutures/commit/1da8d103213b14224614a8bbf70ccd7d07f86fb7), I've changed the way invalidation tokens are used. Instead of passing the token, you can now pass the `token.context` as the execution context, which has the same effect. This enables you to use the invalidation token for all methods that accept an execution context (which are a lot!). Note that this feature is still very much in beta. Let me know what you think!

**Comment by aputinski** [comment]
I think this looks great! Does this mean if the token is not cancelled the callback will be executed in the context in which the token was created?

Thanks again for working on this library — it's been a pleasure to work with!

**Comment by Thomvis** [comment]
If you pass 'token.context', it will execute the closure according to the default threading model ( see readme). If you want more control, you can also pass 'token.context(Queue.main.context)' (instead of the main queue, you can pass any execution context) to make it execute in a specific context.

**Comment by Thomvis** [comment]
As mentioned in my previous comment, I've renamed the property to `validContext`.
