### ISSUE TITLE
ErrorType does not conform ErrorType :/

### ISSUE THREAD

**Issue by icorderi** [Thomvis/BrightFutures#73]
I'll throw this one out there, no clue what's going on.

```swift
let foo: Future<String, ErrorType>
```
**error:** protocol type `ErrorType` does not conform to protocol `ErrorType` because `ErrorType` is not declared **@objc**

```swift
// Custom protocols don't work either
protocol MyError: ErrorType {}

// and trying to make it @objc backfires
@objc public protocol MyObjCError: ErrorType {}
```
**error:** **@objc** protocol `MyObjCError` cannot refine **non-@objc** protocol `ErrorType`

Any wizard has a magic spell to fix this one? 
```swift
// this is ugly
enum FutureError : ErrorType {
    case Error(ErrorType)
}
// and this is not kosher
class FutureError : ErrorType { }
```

> Swift 2.0
> XCode Version 7.0 beta 5 (7A176x)

**Comment by Thomvis** [comment]
For the internal errors, we use a custom enum that explicitly implements the ErrorType protocol and that seems to work fine. A future (or any generic type) can apparently not contain a value that is only restricted to a protocol. What does work is this:

```
func test<E: ErrorType>() -> Future<Int, E> {
...
}
```

I'm closing the issue, because it doesn't seem to be strictly related to BrightFutures, but feel free to continue the discussion.
