### ISSUE TITLE
ERROR ITMS-90060: "This bundle is invalid.

### ISSUE THREAD

**Issue by knutnyg** [Thomvis/BrightFutures#88]
Hello. 

When using BrightFutures 3.0.0 I'm unable to upload the .ipa to iTunes Connect. It looks like its because of a dependency to Result<0.6.0-beta.4> which makes the transporter freak out. 

```
[15:39:57]: [Transporter Error Output]: ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '0.6.0-beta.4' in the Info.plist file must be a period-separated list of at most three non-negative integers."
```

Is it possible to use a released version instead? :)

**Comment by Thomvis** [comment]
Sorry to hear that you're having trouble submitting.

It seems like this is caused by a recent change in the iTunesConnect policy. CocoaPods automatically adds the pod version to the framework's Info.plist and Apple now requires all version strings to be of the %d.%d.%d format. Here's a temporary solution: https://github.com/CocoaPods/CocoaPods/issues/4421#issuecomment-150372394. Hope that works for you!
