### ISSUE TITLE
Set up Gitter Room

### ISSUE THREAD

**Issue by fsvehla** [Thomvis/BrightFutures#90]
It would be great if there would be a Gitter room for BrightFutures

**Comment by Thomvis** [comment]
Thanks for the suggestion!

I have no experience with Gitter myself. Can you provide an example of (a) project(s) where this works well for?

I'll have to admit that I am a bit reserved regarding this idea. There are several ways to get support already, e.g. on Twitter, StackOverflow and issues here on GitHub, none of which are used extensively. I'd be worried that the Gitter room would be empty most of the time. In that case it could do more harm than good, since it will be another place where you could find answers to a hand full of questions.

But, as said, I'd like to hear your motivation and see cases where it works well. Thanks again for the suggestion!

**Comment by mdedetrich** [comment]
Just chipping in here, I mainy program in Scala (started learning Swift recently), and Gitter is a godsend in regards to open source projects

Its basically meant to be a replacement for IRC (not really for stack overflow). For people that have quick and dirty questions, or are looking for general information its really handy. The main thing is, its a really painless integration with github.

**Comment by Thomvis** [comment]
I've just opened a Gitter Room for BrightFutures. Let's try it out. Thanks for the suggestion!
